### PR TITLE
MINOR: update required framework version to ^3.2

### PR DESCRIPTION
**Pull request by SpiritLevel**
Ping @chillu

...first baby step ;)

I notice that addons.silverstripe.org is not responsive, and, that the tool bar on this site isn't properly responsive like it is on www.silverstripe.org. The toolbar on docs.silvertripe.org is also not properly responsive. Will open issues.

Interested in making addons.silverstripe.org responsive ?

### CODE REVIEW

**Comment by chillu** [comment]
Hey David, thanks for doing that! Have you tested operation with 3.2 locally? 3.2 was the first release to follow semver, so I'm not *too* worried about merging this PR and upgrading addons, but would feel better about it knowing that you've given it a quick look.

Responsive addons sounds fantastic! CC'ing in @camfindlay on this.

**Comment by SpiritLevel** [comment]
Yup :) addons installs and works "OK" with 3.2...I did this to get addons up to the stable framework, so all fixes are within this context. Also, I wanted addons to run with the PDO connector for speed. 

While I am looking at everything in addons, in order  to work out how to switch to solr and queuedjobs, I'd happy to try fix other issues. I may need a little help, though, since this will be stretching my limited SS knowledge.

**Comment by tractorcow** [comment]
I'd probably lock it to ~3.2.0@stable, since we would need to re-test against 3.3 once that's stable too.

**Comment by SpiritLevel** [comment]
Ah, OK. Done :) But, I would have thought that something like addons ought to be insensitive to minor version changes in framework. What could break ?

**Comment by camfindlay** [comment]
I'm going to make a branch for the current deployed version (have also tagged 1.1.0 as current stable). Then we can start accepting larger breaking changes on to master.

**Comment by camfindlay** [comment]
I've gone the other way and kept master as a deployable stable and opened a new 2.0 branch. Can you redo this PR on the 2.0 branch and I'll merge in right away. That way we can go to town on this without affecting the live code until we're ready. Thanks @SpiritLevel ! :)

**Comment by SpiritLevel** [comment]
@camfindlay All done :)

**Pull request closed without merging**
