### PR TITLE
FIX Adjust module score from Helpful Robot API to negate the effect o…

### PR DESCRIPTION
**Pull request by camfindlay**
…f Code of Conduct (not currently in module standard)

### CODE REVIEW

**Comment by camfindlay** [comment]
@assertchris any comments on this approach?

**Comment by assertchris** [comment]
Seems fine. Could also try `min(100, $this->HelpfulRobotScore / 92.9 * 100)`, so modules don't automatically get an extra 7.1%...

**Comment by camfindlay** [comment]
nice I'll alter and go with the above. @helpfulrobot seems to be asleep... I suppose it is Sunday.

**Comment by camfindlay** [comment]
Done

**Pull request merged**
