### PR TITLE
Fix SS4-compatibility checking (fixes #160)

### LINKED ISSUE #160: RFC: Module support: >= interpreted as ^
I've been thinking about the module support question as relates to our search.

When someone has set their framework/cms dependency as ">=3.1.0" there are a few possible options:

 * The module maintainer made a mistake
 * The module maintainer, and lo and behold, it worths with both SS3 and SS4. Given renaming this is unlikely, but it might be more likely in future, e.g. "works with SS4 and SS5"
 * The module maintainer has worked to guarantee that it will work with all future versions.

Even if the 2nd option might be the case, the 3rd option is so unlikely that we can ignore it.

As such I think we can afford to deprecate the use of `>=` in our community, instead favouring more explicit multi-version statements such as `^3.1.2 || ^4`.

That being the case, I think we can safely interpret `>=` as `^` when checking compatibility with SilverStripe versions.

### PR DESCRIPTION
**Pull request by sminnee**
This PR has a few changes, but the main functional change is #160.

In addition it also:
 * Adds support for silverstripe-vendormodule
 * Upgrades to SS 3.6
 * Converts tabs to spaces, in keeping with .editorconfig prefs
 * Fix a few bugs

In short it was everything necessary to actually test that #160 was working locally! ;-)

### CODE REVIEW

**Comment by robbieaverill** [comment]
Do you mind pushing a patch to the Travis config to run on PHP 7.0 and 7.1?

**Comment by sminnee** [comment]
@robbieaverill what version does prod run on? we probably only need to test on the current, and possibly the planned, hardware stack

**Comment by robbieaverill** [comment]
@sminnee production runs on PHP 5.4 at the moment. The Travis build is pointing out a dependency which isn't compatible with less than PHP 7 by the looks of it

**Comment by sminnee** [comment]
OK I've set it up to get PHP 5.4 and 7.1 and it's working now.

**Comment by sminnee** [comment]
Hold up, it's possible that this has broken the actual execution of the add-on update script :(

**Comment by sminnee** [comment]
^ False-alarm, all is well.

**Comment by robbieaverill** [comment]
Thanks @sminnee! I'm giving this a whirl on staging now, but it looked good locally

**Comment by sminnee** [comment]
Whoop - nice work! Let's get a prod release shortly; prod is a bit old now and I suspect that there are a few bugs that are fixed in master.

**Comment by robbieaverill** [comment]
It turned out that prod was up to date :-D deploying tomorrow nevertheless

**Pull request merged**
